# Generated by Django 5.2.1 on 2025-05-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='swsid',
            field=models.CharField(default='SWS000', max_length=20, unique=True),
        ),
    ]
