# Generated by Django 5.2.1 on 2025-05-22 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_patient_swsid'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='available_timings',
            field=models.CharField(default='Mon-Fri, 9 AM - 5 PM', max_length=200),
        ),
        migrations.AddField(
            model_name='doctor',
            name='hospital_name',
            field=models.CharField(default='Swaastya Hospital', max_length=100),
        ),
        migrations.AddField(
            model_name='doctor',
            name='swsid',
            field=models.CharField(default='DSWS000', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='swsid',
            field=models.CharField(default='SWP000', max_length=20, unique=True),
        ),
    ]
