# Generated by Django 5.2.1 on 2025-05-22 19:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_doctor_available_timings_doctor_hospital_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='date',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='date',
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reason',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(default='Scheduled', max_length=50),
        ),
        migrations.AddField(
            model_name='billing',
            name='billing_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='billing',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='billing',
            name='service_description',
            field=models.CharField(default='Default Service', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='billing',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='swsid',
            field=models.CharField(default='SWD000', max_length=20, unique=True),
        ),
    ]
